language: php

php: [5.3, 5.4, 5.5]

env:
  - ZEND_FRAMEWORK_VERSION='2.1.*'
  - ZEND_FRAMEWORK_VERSION='2.2.*'
  

branches:
  only:
    - master

before_script:
  - composer self-update
  - composer require --no-update zendframework/zendframework=$ZEND_FRAMEWORK_VERSION
  - composer install --dev --prefer-source 
  
script: 'vendor/bin/behat -c testapp/behat.yml'